events {
    worker_connections 1024;
}

http {

    upstream user_service {
        server user_service:8000;
    }

    upstream music_service {
        server music_service:8000;
    }

    server {
        listen 80;

        location /users/ {
            proxy_pass http://user_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /music/ {
            proxy_pass http://music_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /protected-music/ {
            internal;
            alias /var/www/html/storage/app/private/;
        }
    }
}

